@extends('layouts.default')
@section('content')
    <div class="container">
        <div id="breadcrumb">
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                <a href="/" itemprop="url" class="nopad-l">
                    <span itemprop="title">Trang chủ</span>
                </a>
            </div>
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                &nbsp;/&nbsp;<a href="" itemprop="url">
                    <span itemprop="title">CHÍNH SÁCH ƯU ĐÃI CHO KHÁCH HÀNG GAME-NET</span>
                </a>
            </div>
        </div><!--breadcrumb-->
        <div class="line"></div>
        <div class="clear"></div>
        <div class="nd"><p style="line-height: 1.38; margin-top: 11pt; margin-bottom: 11pt; text-align: center;"><span style="font-size: 14pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CHÍNH SÁCH ƯU ĐÃI CHO KHÁCH HÀNG GAME-NET</span></strong></span></p>
            <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Công ty TNHH Kỹ Nghệ Phúc Anh thành lập từ năm 2000, là doanh nghiệp chuyên cung cấp máy tính, thiết bị văn phòng, thiết bị kỹ thuật số và các giải pháp, ứng dụng công nghệ chuyên sâu. Game – Net là một trong những ứng dụng mà Phúc Anh đầu tư phát triển và áp dụng những công nghệ tiên tiến nhất nhằm đáp ứng nhu cầu phát triển của thị trường.</span></p>
            <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Là đơn vị uy tín, có nhiều năm kinh nghiệm trong lĩnh vực tư vấn, lắp đặt các phòng Game – Net, Phúc Anh đã mở ra một hướng đi mới cho các đơn vị, cá nhân có ý định kinh doanh Game – Net.</span></p>
            <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Phúc Anh cam kết Quý khách hàng sẽ an tâm, hài lòng khi sử dụng các dịch vụ công nghệ của Phúc Anh.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Đến với Phúc Anh, Quý khách hàng sẽ được hưởng các chính sách ưu đãi đặc biệt sau:</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I. CAM KẾT GIÁ BÁN &amp; SẢN PHẨM:</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Cam kết giá bán sản phẩm tới khách hàng là giá tốt nhất thị trường tại thời điểm tư vấn và xây dựng giá bán cho khách hàng.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Cam kết, khách hàng sẽ được hưởng các ưu đãi về giá khi nâng cấp hoặc mua thêm thiết bị về sau.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Cam kết tất cả các hàng hóa bán ra tại Phúc Anh là sản phẩm chính hãng, mới 100%, đầy đủ xuất xứ - tiêu chuẩn chất lượng của nhà sản xuất.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Hỗ trợ tư vấn qua điện thoại, email, chat hoàn toàn miễn phí và khảo sát trực tiếp tại địa điểm của khách hàng, giúp khách hàng khai thác tối đa hiệu quả sử dụng máy để tăng doanh thu, tiết kiệm chi phí. Phúc Anh còn hỗ trợ khách hàng quản lý, vận hành phòng Game – Net một cách đơn giản và hiệu quả nhất.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">II. CHÍNH SÁCH GIAO HÀNG VÀ LẮP ĐẶT TẠI NƠI SỬ DỤNG</span></strong></span></p>
            <table style="border: none; border-collapse: collapse;">
                <tbody>
                <tr style="height: 23pt;">
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Số lượng máy</span></strong></span></p>
                    </td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Khoảng cách tính từ địa chỉ mua hàng (km)</span></strong></span></p>
                    </td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chế độ giao và lắp đặt</span></strong></span></p>
                    </td>
                </tr>
                <tr style="height: 12pt;">
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Từ 30 máy trở lên</span></p>
                    </td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Phạm vi 300 km</span></p>
                    </td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;" rowspan="3">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp; &nbsp; Miễn phí giao và lắp đặt</span></p>
                    </td>
                </tr>
                <tr style="height: 12pt;">
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp; Từ 20 đến 29 máy</span></p>
                    </td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Phạm vi 200 km</span></p>
                    </td>
                </tr>
                <tr style="height: 12pt;">
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Từ 10 đến 19 máy</span></p>
                    </td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Phạm vi 100 km</span></p>
                    </td>
                </tr>
                <tr style="height: 23pt;">
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;" rowspan="2">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Các trường hợp khác</span></p>
                    </td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;" rowspan="2"><span style="font-size: 12pt; font-family: 'times new roman', times;">&nbsp;</span></td>
                    <td style="vertical-align: top; overflow: hidden; overflow-wrap: break-word; border: solid #808080 0.75pt;" rowspan="2">
                        <p style="line-height: 1.38; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp; Theo thỏa thuận giữa khách hàng và Phúc Anh, đảm bảo hỗ trợ khách hàng ở mức tốt nhất</span></p>
                    </td>
                </tr>
                </tbody>
            </table>

            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">III. CHÍNH SÁCH HỖ TRỢ SAU BÁN HÀNG</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Miễn phí bảo trì bảo dưỡng trong 12 tháng đầu tiên hoặc 4 lần/ năm (Áp dụng với các khách hàng trong nội thành Hà Nội).</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Đối với các lỗi cơ bản có thể xử lý từ xa thông qua phần mềm Team Viewer Phúc Anh hỗ trợ khách hàng vào tất cả các ngày trong tuần từ 8h đến 21h (trừ tết âm lịch).</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Các trường hợp lỗi không khắc phục được từ xa Phúc Anh sẽ có mặt tại địa điểm khách hàng để xử lý khắc phục lỗi.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Cụ thể như sau:</span></strong></span></p>
            <table style="border: none; border-collapse: collapse;">
                <tbody>
                <tr style="height: 61pt;">
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Khoảng cách áp dụng</span></strong></span></p>
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><em><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(Từ Phúc Anh đến địa điểm của khách hàng)</span></em></span></p>
                    </td>
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nội dung hỗ trợ khách hàng</span></strong></span></p>
                    </td>
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Thời gian đến địa điểm của khách hàng</span></strong></span></p>
                    </td>
                </tr>
                <tr style="height: 37pt;">
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Phạm vi dưới 20km</span></p>
                    </td>
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Miễn phí 2 lần/ tháng trong vòng 06 tháng kể từ ngày mua</span></p>
                    </td>
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Trong vòng 03 giờ sau khi tiếp nhận được thông báo</span></p>
                    </td>
                </tr>
                <tr style="height: 37pt;">
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Phạm vi từ 20km đến 50km</span></p>
                    </td>
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Miễn phí 1 lần/tháng trong vòng 6 tháng kể từ ngày mua</span></p>
                    </td>
                    <td style="vertical-align: top; padding: 5pt 5pt 5pt 5pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.9960975000000001pt;">
                        <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Trong vòng 6 giờ sau khi nhận được thông báo</span></p>
                    </td>
                </tr>
                </tbody>
            </table>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Trong những trường hợp khác, hai bên sẽ thỏa thuận thời gian để đảm bảo thuận lợi và hiệu quả nhất cho khách hàng.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">IV. CHÍNH SÁCH BẢO HÀNH</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Đổi ngay sản phẩm mới đối với các sản phẩm bị lỗi có thời gian mua trong vòng 03 tháng.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Đổi ngay sản phẩm tương đương đối với các sản phẩm bị lỗi có thời gian mua lớn hơn 03 tháng. Trong trường hợp hết sản phẩm tương đương, chúng tôi sẽ cho mượn ngay 01 sản phẩm thay thế (nếu Quý khách có nhu cầu), trong thời gian chờ bảo hành trong vòng 07 ngày làm việc.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Bảo hành cả trong trường hợp cháy nổ IC, phồng tụ.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Bảo hành miễn phí tại nơi sử dụng trong 02 năm đầu đối với khách hàng trong phạm vi 20km.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Bảo hành miễn phí tại nơi sử dụng 01 lần/1 tháng trong 02 năm đầu sử dụng đối với khách hàng trong phạm vi từ trên 20km- 50km.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Đối với khách hàng trong phạm vi trên 50km:</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">+ Khách hàng gửi hàng lỗi tới TTBH của Phúc Anh ghi rõ lỗi, đóng gói hàng hóa đảm bảo an toàn và niêm phong (nếu cần). Phúc Anh sẽ ưu tiên trả hàng sớm nhất cho khách hàng Game – Net.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">+ Phúc Anh sẽ hỗ trợ chi phí một chiều khi khách hàng gửi tới TTBH.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Các chế độ khác tuân thủ theo chính sách bảo hành của Công ty và Hãng.</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">V. THÔNG TIN LIÊN HỆ:</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1. Khách hàng có nhu cầu lắp đặt mới, cung cấp thiết bị, vui lòng liên hệ:</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hotline: 038.628.6699 (máy lẻ 1)</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2164</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Email:</span></strong> <a style="text-decoration: none;" href="mailto:hitech@phucanh.com.vn"><span style="color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">hitech@phucanh.com.vn</span></a></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Thời gian làm việc</span></strong><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Từ</span><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 8h00 – 21h00 (tất cả các ngày trong tuần trừ ngày lễ, Tết)</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2. Khách hàng có nhu cầu tư vấn hỗ trợ kỹ thuật, xử lý sự cố phát sinh, vui lòng liên hệ:</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hotline:</span></strong> <strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">098.656.1212&nbsp;</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2165</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Email:</span></strong> <a style="text-decoration: none;" href="mailto:tuvankythuat@phucanh.com.vn"><span style="color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">tuvankythuat@phucanh.com.vn</span></a></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Thời gian làm việc</span></strong><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Từ</span><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 8h00 – 17h30 (tất cả các ngày trong tuần trừ ngày lễ, Tết)</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3. Khách hàng có nhu cầu về thông tin bảo hành vui lòng liên hệ:</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Hotline: 096.788.3443</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2173</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Email:</span></strong> <a style="text-decoration: none;" href="mailto:baohanh@phucanh.com.vn"><span style="color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">baohanh@phucanh.com.vn</span></a></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Thời gian làm việc</span></strong><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Từ</span><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 8h00 – 17h30 (tất cả các ngày trong tuần trừ ngày lễ, Tết)</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4. Khách hàng có ý kiến đóng góp về chất lượng dịch vụ, vui lòng liên hệ:</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hotline: 098.656.2424&nbsp;</span></strong></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2174</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Email:</span></strong> <a style="text-decoration: none;" href="mailto:ykienkhachhang@phucanh.com.vn"><span style="color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">ykienkhachhang@phucanh.com.vn&nbsp;</span></a></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Thời gian làm việc</span></strong><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Từ</span><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 8h00 – 20h30 (tất cả các ngày trong tuần trừ ngày lễ, Tết)</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">*</span></strong><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Chat ngay với chúng tôi trên website để nhận thông tin, tư vấn và mua hàng một cách nhanh chóng nhất.</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">* </span></strong><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Để liên hệ trực tiếp tới các </span><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">showroom</span></strong><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, khách hàng gọi tới hotline của cửa hàng:</span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- <strong>SHOWROOM PHÚC ANH 15 XÃ ĐÀN: Điện thoại: (024) 3968 9966 (ext 1)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH TRẦN DUY HƯNG: Điện thoại: (024) 3968 9966 (ext 2)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH 134 THÁI HÀ: Điện thoại: (024) 3968 9966 (ext 3)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH NGUYỄN HOÀNG: Điện thoại: (024) 3968 9966&nbsp;(ext 4)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH 141-143 PHẠM VĂN ĐỒNG: Điện thoại: (024) 3968 9966&nbsp;(ext 5)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH 89 LÊ DUẨN: Điện thoại: (024) 3968 9966&nbsp;(ext 6)</strong></span></span></p>
        </div>
    </div>
@endsection
