@extends('layouts.default')
@section('content')
    <div class="container">
        <div id="breadcrumb">
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                <a href="/" itemprop="url" class="nopad-l">
                    <span itemprop="title">Trang chủ</span>
                </a>
            </div>
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                &nbsp;/&nbsp;<a href="" itemprop="url">
                    <span itemprop="title">Hướng dẫn mua hàng online</span>
                </a>
            </div>
        </div><!--breadcrumb-->
        <div class="line"></div>
        <div class="clear"></div>
        <div class="nd"><p style="text-align: center; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><strong><span style="font-size: 14.0pt; font-family: 'Times New Roman','serif'; color: black;">HƯỚNG DẪN MUA HÀNG ONLINE</span></strong></p>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Quý Khách có thể lựa chọn những cách thức mua hàng trực tuyến sau:</span></strong></p>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><span style="color: #0000ff;"><a style="color: #0000ff;" href="#_I._Mua_hàng"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; text-decoration: none; text-underline: none;">- Mua hàng qua điện thoại</span></strong></a></span></p>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><span style="color: #0000ff;"><a style="color: #0000ff;" href="#_II._Mua_hàng"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; text-decoration: none; text-underline: none;">- Mua hàng qua chat với nhân viên tư vấn (LiveChat, ZaloChat, FacebookChat được tích hợp trên Website Phúc Anh)</span></strong></a></span></p>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><span style="color: #0000ff;"><a style="color: #0000ff;" href="#_III._Đặt_hàng"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; text-decoration: none; text-underline: none;">- Đặt đơn hàng online trên Website Phúc Anh</span></strong></a></span></p>
            <p style="margin-top: 9.0pt; text-align: justify; line-height: normal; background: white;"><span style="color: #0000ff;"><a style="color: #0000ff;" href="#_IV._Gửi_yêu"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; text-decoration: none; text-underline: none;">- Gửi yêu cầu báo giá sản phẩm trên Website Phúc Anh</span></strong></a></span></p>
            <h1 style="margin-top: 0cm;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: windowtext;">I. Mua hàng qua điện thoại.</span></h1>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Quý khách gọi điện thoại trực tiếp đến Tổng đài <strong>1900 2164</strong></span>&nbsp;</p>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">- </span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">Khách hàng cá nhân chọn nhánh số 1 (Thời gian làm việc từ 8h00 đến 21h00 hàng ngày, trừ ngày Tết) hoặc 0974 55 88 11</span></p>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">- Khách hàng doanh nghiệp và dự án chọn nhánh số 2 (Thời gian làm việc từ 8h00 đến 17h30 từ thứ Hai đến thứ Bảy hàng tuần, trừ các ngày Chủ Nhật, ngày lễ, ngày Tết) hoặc 038 658 6699</span></p>
            <p style="text-align: justify; line-height: normal; background: white; margin: 9.0pt 0cm 9.0pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">- Khách hàng muốn liên hệ trực tiếp tới các showroom&nbsp; (Thời gian làm việc từ 8h00 đến 21h00 hàng ngày, trừ ngày Tết).</span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- <strong>SHOWROOM PHÚC ANH 15 XÃ ĐÀN: Điện thoại: (024) 3968 9966 (ext 1) </strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH TRẦN DUY HƯNG: Điện thoại: (024) 3968 9966 (ext 2) </strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH 134 THÁI HÀ: Điện thoại: (024) 3968 9966 (ext 3)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH NGUYỄN HOÀNG: Điện thoại: (024) 3968 9966&nbsp;&nbsp;(ext 4)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH 141-143 PHẠM VĂN ĐỒNG: Điện thoại: (024)&nbsp;3968 9966&nbsp;&nbsp;(ext 5)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong>- SHOWROOM PHÚC ANH 89 LÊ DUẨN: Điện thoại: (024)&nbsp;3968 9966&nbsp;&nbsp;(ext 6)</strong></span></span></p>
            <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong><img src="https://phucanhcdn.com/media/lib/20-10-2022/screenshot_1.jpg" alt="" width="1201" height="246"><br></strong></span></span></p>
            <h1><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: windowtext;">II. Mua hàng qua Chat với nhân viên tư vấn của Phúc Anh (Website, Zalo hoặc Facebook)</span></h1>
            <p><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">1.LiveChat trực tiếp trên Website của Phúc Anh:</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">- Inbox ngay với chúng tôi bằng cách nhấn vào các nút&nbsp;<img src="https://phucanhcdn.com/media/lib/27-10-2021/screenshot_2.png" alt="" width="302" height="30"> &nbsp;<img src="https://phucanhcdn.com/media/lib/27-10-2021/screenshot_3.png" alt="" width="66" height="60">&nbsp; <img src="https://phucanhcdn.com/media/lib/27-10-2021/screenshot_4.png" alt="" width="51" height="51">&nbsp;và tiến hành mua hàng.</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><img src="https://phucanhcdn.com/media/lib/18-10-2022/huong-dan-mua-hang.jpg" alt="" width="1288" height="620"></p>
            <p>&nbsp;<span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">2.Chat trực tiếp trên Fanpage của Phúc Anh:</span></p>
            <p style="margin-bottom: .0001pt; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">- Quý khách inbox ngay Phúc Anh theo link: </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://m.me/PhucAnhSmartWorld"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif';">m.me/PhucAnhSmartWorld</span></strong></a></span><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"> <strong>hoặc</strong> </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://m.me/PhucAnhGamingWorld"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif';">m.me/PhucAnhGamingWorld</span></strong></a></span><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: blue;">&nbsp;</span></strong><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">hoặc</span></strong> <span style="color: #0000ff;"><a style="color: #0000ff;" href="http://m.me/PhucAnhSmartHome"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif';">m.me/PhucAnhSmartHome</span></strong></a></span></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><span style="color: #222222; font-family: 'Times New Roman', serif;"><span style="font-size: 16px;">Fanpage Phúc Anh Smart World:&nbsp;<span style="color: #0000ff;"><strong><a style="color: #0000ff;" href="https://www.facebook.com/phucanhsmartworld">Phúc Anh Smart World - Home | Facebook</a></strong></span><br>Fanpage Phúc Anh Gaming World:&nbsp;<span style="color: #0000ff;"><strong><a style="color: #0000ff;" href="https://www.facebook.com/phucanhgamingworld/">Phúc Anh Gaming World - Home | Facebook</a></strong></span></span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><span style="color: #222222; font-family: 'Times New Roman', serif;"><span style="font-size: 16px;">Fanpage Phúc Anh:&nbsp;<span style="color: #0000ff;"><strong><a style="color: #0000ff;" href="https://www.facebook.com/phucanhsmarthome/">Phúc Anh Smart Home - Home | Facebook</a></strong></span></span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Quý khách sẽ được tư vấn miễn phí và nhanh chóng nhất.</span></p>
            <h1><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: windowtext;">III. Đặt hàng qua hệ thống website Phúc Anh.</span></h1>
            <h2><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: windowtext;">Bước 1: Chọn sản phẩm.</span></h2>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Trên giao diện website có các công cụ hỗ trợ để bạn tìm kiếm sản phẩm như: hộp tìm kiếm, menu danh mục, danh mục sản phẩm. Tìm nhanh sản phẩm bằng cách nhập từ khóa của sản phẩm vào ô tìm kiếm.</span>&nbsp;</p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"><img src="/media/lib/ol6.jpg" alt="" width="1366" height="649"></span></p>
            <h2><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: black;">Bước 2: Đặt hàng</span></h2>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">Bạn đã chọn được sản phẩm ưng ý thì tiến hành đặt hàng bằng cách click chuột vào nút <strong>“MUA NGAY”</strong> hoặc “<strong>MUA TRẢ GÓP”</strong></span></p>
            <p style="margin-bottom: 0.0001pt; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;"><img style="display: block; margin-left: auto; margin-right: auto;" src="/media/lib/ol7.png" alt="" width="659" height="338"></span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Lựa chọn </span><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">“MUA TRẢ GÓP”,</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;"> Quý khách thực hiện theo hướng dẫn </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="https://www.phucanh.vn/chinh-sach-mua-tra-gop.html"><em><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">tại đây.</span></em></a></span></p>

            <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Lựa chọn </span><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">“MUA NGAY”,</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;"> Quý khách tiếp tục thực hiện:</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">Tại trang Giỏ hàng, chọn số lượng sản phẩm muốn mua bằng nút (+) hoặc (-). Nhấn để xóa bỏ sản phẩm đã chọn.</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;"><img src="/media/lib/ol8.png" alt="" width="1345" height="693"></span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">Trong mục mua ngay, bạn sẽ điền vào các thông tin về cá nhân, thông tin về sản phẩm đã chọn, thông tin về cách thức vận chuyển, cách thức thanh toán. Sau khi chọn xong các cách thức vận chuyển, thanh toán bạn click vào nút <strong>"ĐẶT HÀNG"</strong> để hoàn tất.</span></p>
            <p style="margin-bottom: 0.0001pt; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;"><img style="display: block; margin-left: auto; margin-right: auto;" src="/media/lib/ol9.png" alt="" width="651" height="338"></span></p>
            <h2><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: black;">Bước 3: Tiếp tục mua hàng </span></h2>
            <p><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: black;">Nếu bạn muốn chọn mua thêm sản phẩm vào “<strong>GIỎ HÀNG</strong>” của mình thì bấm vào nút "<strong>Tiếp tục mua hàng</strong>".</span></p>
            <p><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: black;"><img src="/media/lib/ol10.png" alt="" width="1510" height="781"></span></p>

            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Bạn có thể vào lại "giỏ hàng" để xem các sản phẩm của bạn đã chọn và hoàn tất các thông tin để tiến hành mua hàng.</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"><img src="/media/lib/ol11.png" alt="" width="1349" height="697"></span></p>
            <h2 style="margin-top: 0cm; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">Bước 4: Lựa chọn phương thức giao</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;"> hàng và thanh toán.</span></h2>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Tùy theo giá trị đơn hàng và khoảng cách vận chuyển đến địa chỉ giao nhận hàng, Phúc Anh sẽ tính chi phí vận chuyển hoặc miễn phí một phần hoặc toàn bộ chi phí vận chuyển đối với đơn hàng đã đặt mua của Quý khách hàng. Tham khảo </span><a href="https://www.phucanh.vn/page/van-chuyen-giao-nhan-hang-hoa" target="_blank"><strong><em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: blue;">Chính sách Vận chuyển &amp; giao nhận hàng hóa</span></em></strong><em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">.</span></em></a></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Quý khách vui lòng lựa chọn một trong các phương thức thanh toán sau:</span></p>
            <h3 style="margin-top: 0cm; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: windowtext;">(1) Thanh toán khi nhận hàng (Tiền mặt/ Quẹt thẻ qua POS)</span><em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: windowtext;"> (Chỉ áp dụng với địa điểm giao hàng có khoảng cách dưới 20Km tính từ địa điểm mua hàng hoặc thông qua các đơn vị trung gian vận chuyển theo thỏa thuận)</span></em></h3>
            <h3 style="margin-top: 0cm; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">(2) Chuyển khoản qua tài khoản ngân hàng </span><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">(<em>Với các đơn hàng có khoảng cách giao từ 20Km, Quý khách vui lòng thanh toán trước cho Phúc Anh giá trị đơn hàng và chi phí vận chuyển (nếu có)</em>)</span></h3>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">- Sau khi ấn <strong>“ĐẶT HÀNG”</strong>, Phúc Anh sẽ gửi tới quý khách <strong>“Xác nhận tiếp nhận đơn đặt hàng” </strong>của Quý khách<strong>:</strong></span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"><img src="/media/lib/ol12.png" alt="" width="1347" height="687"></span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">- Trong vòng 30 phút (giờ làm việc) tiếp theo, bộ phận bán hàng trực tuyến sẽ liên hệ tới Quý khách qua <strong>“Số điện thoại liên hệ”</strong> để xác nhận.</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">- Quý khách hàng thực hiện việc chuyển khoản qua ngân hàng tổng số tiền mua hàng, cước vận chuyển (nếu có) vào tài khoản của Phúc Anh (ghi rõ nội dung nộp tiền là thanh toán tiền mua (tên sản phẩm) cho công ty Phúc Anh). Phúc Anh sẽ thực hiện giao dịch ngay sau khi nhận được tiền chuyển khoản từ Quý khách.</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">- Quý khách chuyển tiền cho chúng tôi vào tài khoản sau đây:</span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; text-indent: 36.0pt; line-height: 150%; background: white;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">Tên tài khoản:</span></strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;"> <strong>CÔNG TY TNHH KỸ NGHỆ PHÚC ANH</strong></span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; text-indent: 36.0pt; line-height: 150%; background: white;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Địa chỉ:</span></strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"> <strong>số 15 Xã Đàn, phường Phương Liên, quận Đống Đa, Thành phố Hà Nội</strong> </span></p>
            <table style="width: 100.0%; background: white; border-collapse: collapse;" width="100%">
                <tbody>
                <tr style="height: 1.0pt;">
                    <td style="width: 54.28%; border: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 1.0pt;" width="54%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Tên Ngân hàng</span></strong></p>
                    </td>
                    <td style="width: 26.9%; border: solid #DDDDDD 1.0pt; border-left: none; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 1.0pt;" width="26%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Địa chỉ</span></strong></p>
                    </td>
                    <td style="width: 18.8%; border: solid #DDDDDD 1.0pt; border-left: none; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 1.0pt;" width="18%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Số tài khoản</span></strong></p>
                    </td>
                </tr>
                <tr style="height: 28.8pt;">
                    <td style="width: 54.28%; border: solid #DDDDDD 1.0pt; border-top: none; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="54%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Ngân hàng TMCP Đầu tư và phát triển Việt Nam (<strong>BIDV</strong>)</span></p>
                    </td>
                    <td style="width: 26.9%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="26%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Chi nhánh Đông Đô</span></p>
                    </td>
                    <td style="width: 18.8%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="18%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">1251.0000.080393</span></p>
                    </td>
                </tr>
                <tr style="height: 21.6pt;">
                    <td style="width: 54.28%; border: solid #DDDDDD 1.0pt; border-top: none; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 21.6pt;" width="54%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Ngân hàng TMCP Quân đội (<strong>MB Bank</strong>)</span></p>
                    </td>
                    <td style="width: 26.9%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 21.6pt;" width="26%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Chi nhánh Hoàn Kiếm</span></p>
                    </td>
                    <td style="width: 18.8%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 21.6pt;" width="18%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">067.11.000.32.009</span></p>
                    </td>
                </tr>
                <tr style="height: 28.8pt;">
                    <td style="width: 54.28%; border: solid #DDDDDD 1.0pt; border-top: none; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="54%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Ngân hàng TMCP Kỹ thương Việt Nam (<strong>Techcombank</strong>)</span></p>
                    </td>
                    <td style="width: 26.9%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="26%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Trung tâm Giao dịch Hội Sở</span></p>
                    </td>
                    <td style="width: 18.8%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="18%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">191.2226.8888.011</span></p>
                    </td>
                </tr>
                <tr style="height: 28.8pt;">
                    <td style="width: 54.28%; border: solid #DDDDDD 1.0pt; border-top: none; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="54%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Ngân hàng TMCP Ngoại thương Việt Nam (<strong>Vietcombank</strong>)</span></p>
                    </td>
                    <td style="width: 26.9%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="26%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Chi nhánh Hà Nội</span></p>
                    </td>
                    <td style="width: 18.8%; border-top: none; border-left: none; border-bottom: solid #DDDDDD 1.0pt; border-right: solid #DDDDDD 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt; height: 28.8pt;" width="18%">
                        <p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">0021.000.272.878</span></p>
                    </td>
                </tr>
                </tbody>
            </table>
            <h3 style="line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">(3) Thanh toán trực tuyến (bằng thẻ ATM, VISA, MASTER):</span></h3>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: #222222;">- Sau khi ấn <strong>“ĐẶT HÀNG”</strong>, quý khách vui lòng kiểm tra lại thông tin đơn hàng, chọn <strong>“Thanh toán”<br> <br> </strong></span><img src="/media/lib/ol13.png" alt="" width="1273" height="697"></span></p>
            <p style="margin-bottom: .0001pt; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">Quý khách vui lòng điền thông tin thẻ ATM, VISA, MASTER và chọn <strong>“Thanh toán Số tiền”</strong></span></p>
            <p style="margin-bottom: .0001pt; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;"><img style="display: block; margin-left: auto; margin-right: auto;" src="/media/lib/8.png" alt="" width="660" height="660"><br></span></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Trong vòng 30 phút (giờ làm việc), bộ phận bán hàng trực tuyến sẽ liên hệ lại Quý khách qua <strong>“Số điện thoại liên hệ”</strong> để xác nhận và thực hiện giao dịch ngay sau khi nhận được tiền thanh toán của quý khách.</span></p>
            <h3 style="line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">(4) Trả góp qua Thẻ tín dụng</span></h3>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Quý khách thực hiện theo hướng dẫn </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="https://www.phucanh.vn/chinh-sach-mua-tra-gop.html"><em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif';">tại đây.</span></em></a></span></p>
            <h3 style="line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">(5) Thanh toán Online qua VNpay (bằng thẻ ATM, VISA, MASTER, quét mã QR VNpay):</span></h3>
            <p style="margin-bottom: .0001pt; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">- Sau khi ấn <strong>“ĐẶT HÀNG”</strong>, Quý khách kiểm tra lại thông tin và chọn <strong>“Thanh toán”</strong></span></p>
            <p style="margin-bottom: .0001pt; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"><img src="/media/lib/ol15.png" alt="" width="1035" height="525"></span></p>
            <p style="text-align: justify; line-height: normal; background: white;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">- Thực hiện lựa chọn tiếp phương thức thanh toán:</span></strong></p>
            <p style="text-align: justify; line-height: normal; background: white;"><strong><img src="/media/lib/ol16.png" alt="" width="1105" height="591"></strong></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Tiếp tục lựa chọn quét mã VNPAY hoặc VNPAY ví điện tử, quý khách sẽ nhận được 01 mã QR Code tương ứng với giao dịch:</span></strong></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><strong><img src="/media/lib/ol17.png" alt="" width="1047" height="689"></strong></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Tiếp theo, từ màn hình ứng dụng <strong>Ví điện tử VNPAY</strong>, quý khách chọn <strong>Thanh toán QR</strong> và quét mã QR (đưa mã vào trung tâm của Camera), thực hiện tiếp các yêu cầu của ví điện tử.</span></p>
            <p style="line-height: 150%; background: white; text-align: center;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;"><img src="/media/lib/ol18.png" alt="" width="621" height="542"></span></p>
            <p style="margin-bottom: 0.0001pt; line-height: normal; background: white; text-align: center;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">Trường hợp quý khách lựa chọn thanh toán qua ATM và tài khoản ngân hàng, quý khách có thể tham khảo lại <em>Bước 4 – Mục</em> <em>(3)Thanh toán trực tuyến (bằng thẻ ATM, VISA, MASTER)</em></span></strong></p>
            <p style="text-align: justify; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: #222222;">Trong vòng 30 phút (giờ làm việc), bộ phận bán hàng trực tuyến sẽ liên hệ lại Quý khách qua <strong>“Số điện thoại liên hệ”</strong> để xác nhận và thực hiện giao dịch ngay sau khi nhận được tiền thanh toán của quý khách.</span></p>
            <h1><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: black;">IV. Gửi yêu cầu báo giá sản phẩm trên Website Phúc Anh</span></h1>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">Khách hàng doanh nghiệp có nhu cầu mua hàng hoặc nhu cầu gửi báo giá có thể gửi yêu cầu theo hướng dẫn sau:</span></p>
            <p style="text-align: justify; line-height: normal; background: white;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Cách 1:</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;"> Quý khách chọn biểu tượng&nbsp;<img src="https://phucanhcdn.com/media/lib/27-10-2021/screenshot_6.png" alt="" width="173" height="37">&nbsp;</span> <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">&nbsp;và lựa chọn gửi yêu cầu báo giá, đặt hàng.</span></p>
            <p style="text-align: justify; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;"><img src="https://phucanhcdn.com/media/lib/20-10-2022/screenshot_2.jpg" alt="" width="1222" height="597"><br></span></p>

            <p style="text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">Điền đầy đủ thông tin <em>(bắt buộc với trường có dấu *)</em> và ghi rõ nội dung yêu cầu. Quý khách nên gửi kèm hình ảnh sản phẩm hoặc danh sách sản phẩm cần Phúc Anh cung cấp. Sau đó <strong>“GỬI YÊU CẦU”</strong></span></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><img src="https://phucanhcdn.com/media/lib/27-10-2021/screenshot_9.png" alt="" width="1439" height="749"></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">Cách 2:</span></strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;"> Quý khách kéo màn hình xuống chân Website, chọn khu vực “<strong>Hỗ trợ khách hàng – Yêu cầu báo giá”</strong></span></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><img src="https://phucanhcdn.com/media/lib/27-10-2021/screenshot_8.png" alt="" width="1437" height="747"></p>
            <p style="text-align: justify; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Quý khách thực hiện điền thông tin <strong><em>như Cách 1</em></strong></span></p>
            <p style="text-align: justify; line-height: normal; background: white;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;"><img src="/media/lib/ol23.png" alt="" width="1259" height="693"></span></p>
            <p style="text-align: justify; line-height: 150%; background: white;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: #222222;">Trong vòng 30 phút (giờ làm việc, từ 08h00 đến 17h30), bộ phận bán hàng trực tuyến sẽ liên hệ lại Quý khách qua <strong>“Số điện thoại liên hệ”</strong> để xác nhận và thực hiện yêu cầu của quý khách. Ngoài thời gian làm việc kể trên, Phúc Anh sẽ liên hệ ngay với Quý khách vào ngày làm việc tiếp theo. </span></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><strong><em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">*Lưu ý:</span></em></strong></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">- Quý khách hàng vui lòng cung cấp thông tin chính xác như: địa chỉ, số điện thoại để Phúc Anh có thể liên lạc được với Quý khách.</span></em></p>
            <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Times New Roman','serif'; color: black;">- Quý khách vui lòng đọc kỹ các điều khoản giao dịch, chính sách vận chuyển, phương thức thanh toán trước khi mua hàng.</span></em></p>
            <p style="text-align: right; line-height: normal; background: white;"><strong><em><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; color: black;">Phúc Anh Smart World</span></em></strong></p></div>
    </div>
@endsection
