@extends('layouts.default')
@section('content')
    <div class="container">
        <div id="breadcrumb">
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                <a href="/" itemprop="url" class="nopad-l">
                    <span itemprop="title">Trang chủ</span>
                </a>
            </div>
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                &nbsp;/&nbsp;<a href="" itemprop="url">
                    <span itemprop="title">CHÍNH SÁCH KINH DOANH</span>
                </a>
            </div>
        </div><!--breadcrumb-->
        <div class="line"></div>
        <div class="clear"></div>
        <div class="nd"><div style="text-align: justify;" align="center">
                <p style="line-height: 1.38; text-align: center; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CHÍNH SÁCH KINH DOANH</span></strong></span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Với định hướng khách hàng là trung tâm của mọi hoạt động, NIIT-ICT Hà Nội cam kết mang đến cho khách hàng sự hài lòng cao nhất bằng chất lượng sản phẩm, giá cả cạnh tranh, tư vấn chuyên nghiệp và thái độ phục vụ tận tâm. Phương châm hành động “Kỷ luật – Sáng tạo – Trách nhiệm” giúp Cán bộ - Nhân viên công ty NIIT-ICT Hà Nội luôn hành động chuẩn mực nhưng linh hoạt đảm bảo đáp ứng tốt nhất mọi nhu cầu và sự tin tưởng của khách hàng.</span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">NIIT-ICT Hà Nội xây dựng và áp dụng chính sách kinh doanh thống nhất trong toàn hệ thống với mong muốn đạt được sự hài lòng cao nhất của khách hàng.</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1. </span></strong><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chúng tôi cung cấp sản phẩm chính hãng</span></strong></span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Là đối tác cao cấp của các tập đoàn công nghệ hàng đầu thế giới như: ASUS,&nbsp; APPLE, CANON, DELL, MICROSOFT, HP, INTEL, SONY, SAMSUNG, LG, KINGSTON, MSI,… NIIT-ICT Hà Nội cam kết cung cấp các sản phẩm chính hãng với chất lượng đã được kiểm định và có nguồn gốc xuất xứ rõ ràng.</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2. </span></strong><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chúng tôi đưa ra mức giá cạnh tranh nhất&nbsp;</span></strong></span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Hệ thống kiểm tra giá thị trường cập nhật liên tục, đảm bảo các sản phẩm của NIIT-ICT Hà Nội được bán ra với giá hợp lý nhất. Cùng với đó là các chương trình khuyến mãi hấp dẫn dành cho khách hàng được triển khai thường xuyên và nhiều ưu đãi đặc biệt dành cho các đơn hàng lớn, các khách hàng thân thiết mang lại lợi ích thiết thực nhất cho khách hàng khi mua hàng tại NIIT-ICT Hà Nội.</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Xem thêm&nbsp;</span></strong></span></p>
                <ul>
                    <li style="list-style-type: disc; font-size: 12pt; font-family: 'Times New Roman'; color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="color: #0000ff;"><strong><a style="color: #0000ff;" href="https://www.phucanh.vn/chinh-sach-uu-dai-cho-khach-hang-doanh-nghiep.html">Chính sách ưu đãi dành cho khách hàng doanh nghiệp</a></strong></span></li>
                </ul>
                <ul>
                    <li style="list-style-type: disc; font-size: 12pt; font-family: 'Times New Roman'; color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #0000ff;"><strong><span style="background-color: transparent; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;"><a style="text-decoration: underline; color: #0000ff;" href="https://www.phucanh.vn/chinh-sach-game-net.html">Chính sách ưu đãi dành cho khách hàng Game – Net</a></span></strong></span></li>
                </ul>
                <p><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3. </span></strong><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chúng tôi cung cấp giải pháp đồng bộ phần cứng và phần mềm hỗ trợ&nbsp;</span></strong></span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Không chỉ cung cấp hệ thống phần cứng tổng thể, chúng tôi còn phát triển các phần mềm hỗ trợ hiệu quả để mang tới giá trị sử dụng cao nhất đối với chi phí đầu tư của khách hàng.</span></p>
                <p><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4. </span></strong><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chúng tôi triển khai dịch vụ sau bán hàng hoàn hảo&nbsp;</span></strong></span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Giao hàng miễn phí lên tới 300km theo </span><a style="text-decoration: none;" href="https://www.phucanh.vn/van-chuyen-giao-nhan-hang-hoa.html"><strong><span style="color: #3366ff; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">chính sách vận chuyển &amp; giao nhận</span></strong></a><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, bảo trì - bảo dưỡng miễn phí, bảo hành tại nơi sử dụng... đảm bảo khách hàng luôn an tâm khi sử dụng các sản phẩm được cung cấp bởi NIIT-ICT Hà Nội.</span></span></p>
                <p><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5. </span></strong><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chúng tôi cam kết hỗ trợ kỹ thuật mọi lúc mọi nơi</span></strong></span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Các chuyên viên kỹ thuật trình độ cao và tận tình của NIIT-ICT Hà Nội luôn sẵn sàng hỗ trợ khách hàng xử lý những vấn đề phát sinh trong quá trình sử dụng thông qua hệ thống tư vấn kỹ thuật online.</span></p>
                <p><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6. Chính sách đổi trả sản phẩm miễn phí </span></strong></span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Chúng tôi là đơn vị dẫn đầu trong việc áp dụng chính sách đổi trả sản phẩm miễn phí lên tới 30 ngày. Chi tiết xin vui lòng liên hệ với nhân viên tư vấn của NIIT-ICT Hà Nội.</span></p>
                <p style="line-height: 1.38; text-indent: 36pt; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">NIIT-ICT Hà Nội trân trọng cảm ơn và mong muốn nhận được những ý kiến quý báu của Quý khách.</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">THÔNG TIN LIÊN HỆ</span></strong></span></p>
                <p><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1. Khách hàng có nhu cầu lắp đặt mới, cung cấp thiết bị, vui lòng liên hệ:</span></strong></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- &nbsp; Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2164</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- &nbsp; Máy lẻ 1:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Bán hàng Trực tuyến; Email: </span><a style="text-decoration: none;" href="mailto:banhangonline@phucanh.com.vn"><span style="color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">banhangonline@phucanh.com.vn</span></a><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;hoặc Hotline: 0974.55.88.11</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- &nbsp; Máy lẻ 2:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Bán hàng Dự án &amp; Doanh nghiệp; Email: </span><span style="color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;"><a href="mailto:kdda@phucanh.com.vn">kdda@phucanh.com.vn</a> </span><span style="color: #000000;"><span style="background-color: transparent; font-weight: 400; font-variant: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">hoặc Hotline: </span><span style="background-color: transparent; font-weight: 400; font-variant: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">0386.58.66.99</span><span style="background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;"><br></span></span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2. Địa chỉ các Showroom</span></strong></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">NIIT-ICT Hà Nội</span></span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 15 Xã Đàn, Phương Liên, Đống Đa, Hà Nội. &nbsp; &nbsp; </span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Điện thoại: (024) 3968 9966 (ext 1)</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">NIIT-ICT Hà Nội</span></span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 134 Thái Hà, Đống Đa, Hà Nội.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Điện thoại: (024) 3968 9966 (ext 3)</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">NIIT-ICT Hà Nội</span></span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 152 -154 Trần Duy Hưng, Cầu Giấy, Hà Nội. &nbsp; &nbsp; </span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Điện thoại: (024) 3968 9966 (ext 2)</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">NIIT-ICT Hà Nội</span></span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 141-143 Phạm Văn Đồng - Cầu Giấy - Hà Nội&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Điện thoại: (024) 3968 9966 (ext 5)</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- </span><strong><span style="color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">NIIT-ICT Hà Nội</span></span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 89 Lê Duẩn - Cửa Nam - Hoàn Kiếm - Hà Nội&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-family: 'times new roman', times; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap; font-size: 12pt;">Điện thoại: (024) 3968 9966 (ext 6)</span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3. Khách hàng có nhu cầu hỗ trợ kỹ thuật, xử lý sự cố phát sinh, vui lòng liên hệ:</span></strong></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp; Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2165</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- &nbsp; Email:</span></strong> <span style="color: #3366ff; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><a href="mailto:helpdesk@phucanh.com.vn">helpdesk@phucanh.com.vn</a></span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4. Khách hàng có nhu cầu về thông tin bảo hành vui lòng liên hệ:</span></strong></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp; Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2173</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- &nbsp; Email:</span></strong> <span style="color: #3366ff; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><a href="mailto:baohanh@phucanh.com.vn">baohanh@phucanh.com.vn</a></span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5. Khách hàng có ý kiến đóng góp về chất lượng dịch vụ, vui lòng liên hệ:</span></strong></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- &nbsp; Tổng đài:</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> 1900 2174</span></span></p>
                <p style="line-height: 1.38; text-align: justify; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp; &nbsp; Email</span></strong><span style="color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: </span><span style="color: #0000ff; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">ykienkhachhang@phucanh.com.vn</span></span></p>

                <p style="line-height: 1.38; text-align: right; margin-top: 11pt; margin-bottom: 11pt;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><strong><span style="color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">NIIT-ICT Hà Nội Smart World</span></strong></span></p>

            </div></div>
    </div>
@endsection
