@extends('layouts.default')
@section('content')
    <div class="container">
        <div id="breadcrumb">
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                <a href="/" itemprop="url" class="nopad-l">
                    <span itemprop="title">Trang chủ</span>
                </a>
            </div>
            <div itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                &nbsp;/&nbsp;<a href="" itemprop="url">
                    <span itemprop="title">Điều khoản giao dịch</span>
                </a>
            </div>
        </div><!--breadcrumb-->
        <div class="line"></div>
        <div class="clear"></div>
        <div class="nd">
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: center; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 16.0pt; line-height: 150%; color: black;">ĐIỀU KHOẢN GIAO DỊCH</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: black;">Chào mừng Quý khách đến với website </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://www.phucanh.vn/"><strong><span style="font-size: 11.0pt; line-height: 150%;">www.phucanh.vn</span></strong></a></span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-indent: 36.0pt; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: black;">Quý khách vui lòng đọc kỹ các điều khoản giao dịch dưới đây trước khi bắt đầu vào xem, tham khảo, yêu cầu báo giá, tư vấn cũng như đặt mua các sản phẩm của Chúng tôi. Bằng việc sử dụng các dịch vụ trên website </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://www.phucanh.vn/"><strong><span style="font-size: 11.0pt; line-height: 150%;">www.phucanh.vn</span></strong></a></span><span style="font-size: 11.0pt; line-height: 150%; color: black;">, Quý khách được coi như đã chấp nhận và đồng ý với các điều khoản giao dịch này. </span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-indent: 36.0pt; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Mọi phát sinh, tranh chấp, khiếu nại bao gồm việc khai thác, sử dụng các tư liệu, dữ liệu, thông tin có trong trang web đều nằm dưới sự chi phối của luật pháp Việt Nam.</span></p>
            <p><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">&nbsp;I.TRÁCH NHIỆM, NGHĨA VỤ CỦA CÁC BÊN THAM GIA GIAO DỊCH</span></strong></span></p>
            <p><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">1.Trách nhiệm, nghĩa vụ của Công ty Phúc Anh</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">1.1. Trách nhiệm về thông tin đăng tải trên Website </span></strong><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://www.phucanh.vn/"><strong><span style="font-size: 11pt; line-height: 150%; text-decoration: none;">www.phucanh.vn</span></strong></a></span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Chúng tôi cung cấp lên website này các nội dung, thông tin từ các nguồn thông tin đáng tin cậy và chính xác.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Hình ảnh sản phẩm đăng tải trên website chỉ mang tính chất minh hoạ. NIIT-ICT cam kết sẽ cố gắng đưa lên website những hình ảnh về sản phẩm rõ ràng, dễ nhìn và chính xác nhất.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: black;">- Giá thành sản phẩm được quảng cáo trên website </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://www.phucanh.vn/"><strong><span style="font-size: 11.0pt; line-height: 150%;">www.phucanh.vn</span></strong></a></span><span style="font-size: 11.0pt; line-height: 150%; color: black;"> là giá dùng để đặt hàng trên Website. NIIT-ICT cố gắng và cam kết niêm yết giá một cách chính xác và cập nhật hàng ngày. Tuy nhiên, trong một số ít trường hợp, giá của một số sản phẩm có thể khác với giá niêm yết trên website (do một số mặt hàng có tần suất thay đổi giá và tình trạng sản phẩm thay đổi rất nhanh). Do vậy, Quý khách hàng có thể gặp phải trường hợp giá hoặc tình trạng hàng hoá của sản phẩm không chính xác mà không kịp thông báo. Khi nhận được yêu cầu đặt hàng của Quý khách nếu có sự thay đổi về giá của sản phẩm hay các thông tin khác, chúng tôi sẽ liên lạc trực tiếp hoặc thông báo qua địa chỉ email mà Quý khách cung cấp cho chúng tôi.</span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Giá cập nhật trên website là giá bán lẻ của sản phẩm (đã bao gồm VAT) được áp dụng trên toàn quốc.&nbsp;</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Mặc dù NIIT-ICT tin tưởng rằng các nội dung đã đăng tải là chính xác và hoàn thiện nhưng NIIT-ICT không đại diện hoặc đảm bảo rằng các thông tin trên website này là hoàn toàn chính xác. Tuy nhiên, NIIT-ICT cam kết sẽ thông tin sớm về những lỗi liên quan tới việc đăng tải thông tin không chính xác và khắc phục trong thời gian nhanh nhất.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">1.2. Trách nhiệm trong việc cung cấp hàng hoá</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Công ty NIIT-ICT có nghĩa vụ cung cấp hàng đủ số lượng, chất lượng tốt theo đúng thời gian và các thỏa thuận khác trong đơn đặt hàng hoặc hợp đồng mua bán hàng hóa đã ký kết giữa Công ty NIIT-ICT và khách hàng.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">1.3. Trách nhiệm bảo mật thông tin khách hàng</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">Chi tiết tham khảo <span style="color: #0000ff;"><em>“Chính sách bảo mật thông tin khách hàng”</em></span></span><a href="https://www.phucanh.vn/page/quy-dinh-truy-cap-website"><strong><em><span style="font-size: 11.0pt; line-height: 150%;">Tại đây</span></em></strong></a></span></p>
            <p><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">2.Nghĩa vụ của khách hàng</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Cung cấp đầy đủ, chính xác thông tin mà Công ty NIIT-ICT yêu cầu khi thực hiện các giao dịch.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Thanh toán đơn hàng theo đúng thời gian đã thoả thuận trong đơn đặt hàng hoặc hợp đồng mua bán hàng hóa đã ký kết giữa Công ty NIIT-ICT và khách hàng.</span></p>
            <p><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">3.Giải quyết khiếu nại của khách hàng</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: #222222; font-family: 'times new roman', times;">NIIT-ICT tiếp nhận khiếu nại qua các hình thức sau:</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: #222222; font-family: 'times new roman', times;">- Trực tiếp tại các cửa hàng của Phúc Anh.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: #222222; font-family: 'times new roman', times;">- Qua tổng đài giải quyết khiếu nại 1900 2174 (8h00 -20h30)</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">- Tại mục "Gửi góp ý, khiếu nại" với đường dẫn:<span style="color: #0000ff;">&nbsp;</span></span><span style="color: #0000ff;"><a style="color: #0000ff;" href="https://www.phucanh.vn/gui-y-kien"><strong><em><span style="font-size: 11.0pt; line-height: 150%; text-decoration: none; text-underline: none;">https://www.phucanh.vn/gui-y-kien</span></em></strong></a></span></span></p>
            <p><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">II.HƯỚNG DẪN MUA HÀNG</span></strong></span></p>
            <p><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">1.Quý khách có thể sử dụng 01 trong 02 phương thức sau để mua hàng tại Công ty Phúc Anh:</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Cách 1:</span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;"> Mua hàng trực tiếp tại </span><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">tại 1 trong các showroom của công ty:</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">- Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">Phúc Anh&nbsp;</span></span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">15 Xã Đàn, Đống Đa, Hà Nội.</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- <strong>Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">Phúc Anh</span></strong>&nbsp;134 Thái Hà, Đống Đa, Hà Nội.</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- <strong>Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">Phúc Anh</span></strong>&nbsp;152-154 Trần Duy Hưng, Cầu Giấy, Hà Nội.</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- <strong>Showroom&nbsp;<span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">Phúc Anh</span></strong>&nbsp;89 Lê Duẩn, Cửa Nam, Hoàn Kiếm, Hà Nội.</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: black;">- <strong>Showroom <span style="font-size: 12.0pt; font-family: 'Times New Roman','serif';">Phúc Anh</span></strong>&nbsp;141-143&nbsp;Phạm Văn Đồng, Cầu Giấy, Hà Nội.</span><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">&nbsp;</span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-indent: 18.0pt; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Thời gian từ 8h00 tới 21h00 tại các showroom vào tất cả các ngày trong tuần (trừ ngày Tết).</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Cách 2:</span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;"> Mua hàng online thông qua các hình thức:</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">(1) Mua hàng qua điện thoại:</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">- Phòng bán hàng trực tuyến:</span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;"> 1900 2164 (máy lẻ 1) - Hotline:&nbsp;0974 55 88 11<br></span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Làm việc từ 8h00 – 21h hàng ngày (trừ ngày Tết)</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">- Phòng bán hàng Dự án &amp; Doanh nghiệp:</span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;"> 1900 2164&nbsp;(máy lẻ 2) - Hotline:&nbsp;038 658 6699</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Thời gian từ 8h00 đến 17h30 vào tất cả các ngày trong tuần (trừ CN, ngày Tết, Lễ)</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">- Hệ thống showroom:</span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">&nbsp;</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Thời gian từ 8h00 đến 21h vào tất cả các ngày trong tuần (trừ ngày Tết)</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: #1c1e21; background: white;">(2) </span><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">Chat trực tiếp với nhân viên tư vấn của Phúc Anh:</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: #222222; font-family: 'times new roman', times;">- Bật cửa sổ chat trên Website và đặt câu hỏi để được tư vấn chi tiết.</span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: #1c1e21; background: white; font-family: 'times new roman', times;">- Chat qua Zalo theo số điện thoại tại khu vực &nbsp;trên đầu Website</span></p>
            <p style="line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">- Inbox ngay </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://m.me/PhucAnhSmartWorld"><strong><span style="font-size: 11.0pt; line-height: 150%;">m.me/PhucAnhSmartWorld</span></strong></a></span><strong><span style="font-size: 11.0pt; line-height: 150%; color: #222222;"> hoặc </span></strong><span style="color: #0000ff;"><a style="color: #0000ff;" href="http://m.me/PhucAnhGamingWorld"><strong><span style="font-size: 11.0pt; line-height: 150%;">m.me/PhucAnhGamingWorld</span></strong></a></span><strong><span style="font-size: 11.0pt; line-height: 150%; color: blue;">&nbsp;</span></strong><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">hoặc</span></strong><span style="color: #0000ff;"> <a style="color: #0000ff;" href="http://m.me/PhucAnhSmartHome"><strong><span style="font-size: 11.0pt; line-height: 150%;">m.me/PhucAnhSmartHome</span></strong></a></span><span style="font-size: 11.0pt; line-height: 150%; color: #1c1e21; background: white;"> để được tư vấn!</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: black;">(3) Đặt đơn hàng online trên Website NIIT-ICT (Truy cập vào website </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="https://www.phucanh.vn/page/huong-dan-mua-hang-online"><strong><span style="font-size: 11.0pt; line-height: 150%;">www.phucanh.vn</span></strong></a>,</span><span style="font-size: 11.0pt; line-height: 150%; color: black;"> chọn sản phẩm và gửi đơn đặt hàng Online - thời gian Online 24/24).</span></span></p>
            <p style="text-align: justify; line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: black;">(4) Gửi yêu cầu báo giá sản phẩm trên Website Phúc Anh, chi tiết </span><span style="color: #0000ff;"><a style="color: #0000ff;" href="https://www.phucanh.vn/yeu-cau-dat-hang"><strong><em><span style="font-size: 11.0pt; line-height: 150%; background: white;">Tại đây</span></em></strong></a></span></span></p>
            <p><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">2.Để Quý khách mua hàng nhanh chóng và tiện lợi,</span></strong> <strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">NIIT-ICT xin hướng dẫn các bước mua hàng như sau:</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Bước 1: Lựa chọn hàng hoá</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Mua hàng tại các Showroom:</span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;"> Sau khi lựa chọn được sản phẩm và số lượng phù hợp, Quý khách vui lòng thông báo cho nhân viên NIIT-ICT để được tư vấn và lập đơn hàng.</span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Mua hàng Online:</span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;"> Sau khi lựa chọn được sản phẩm và số lượng phù hợp Quý khách nhấn vào chữ <strong>MUA HÀNG</strong> hoặc biểu tượng <strong>GIỎ HÀNG </strong>&nbsp;ngay bên dưới mỗi sản phẩm.</span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Xem hướng dẫn </span></strong><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">mua hàng Online<strong> chi tiết tại đây:</strong></span></strong><span style="color: #0000ff;"><span style="font-size: 11pt; line-height: 150%;">&nbsp;</span><a style="color: #0000ff;" href="https://www.phucanh.vn/page/huong-dan-mua-hang-online"><strong><em><span style="font-size: 11.0pt; line-height: 150%;">https://www.phucanh.vn/page/huong-dan-mua-hang-online</span></em></strong></a></span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Bước 2: Lựa chọn phương thức giao hàng, thanh toán</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><span style="font-size: 11.0pt; line-height: 150%; color: black;">Để có thêm các thông tin chi tiết về các hình thức giao hàng, thanh toán hiện nay của Phúc Anh, Quý khách hàng vui lòng xem tại mục </span><a href="https://www.phucanh.vn/page/van-chuyen-giao-nhan-hang-hoa"><strong><span style="font-size: 11.0pt; line-height: 150%;">Chính sách vận chuyển &amp; giao nhận</span></strong></a> <span style="font-size: 11.0pt; line-height: 150%; color: black;">và </span><a href="https://www.phucanh.vn/page/phuong-thuc-thanh-toan"><strong><span style="font-size: 11.0pt; line-height: 150%;">Phương thức thanh toán</span></strong></a><span style="font-size: 11.0pt; line-height: 150%; color: black;">.</span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Bước 3: Ký hợp đồng, đơn đặt hàng (nếu cần)</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Khi được yêu cầu ký hợp đồng/ đơn đặt hàng/ gửi báo giá, Công ty NIIT-ICT và Quý khách sẽ làm báo giá hoặc đơn đặt hàng hoặc hợp đồng, thanh lý và gửi qua đường email, qua hình thức chuyển phát nhanh cho bên đối tác, hai bên sẽ xác nhận đặt hàng, ký hợp đồng và gửi lại cho nhau.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Bước 4: Tiến hành thanh toán và giao nhận hàng</span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Sau khi lựa chọn phương thức thanh toán và giao nhận hàng, Quý khách vui lòng:</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Mua hàng tại các Showroom: </span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-indent: 18.0pt; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">1) Thực hiện thanh toán và xác nhận với bộ phận Thu Ngân – Kế toán cửa hàng. </span></p>
            <p style="line-height: 150%; background: white; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">2) Nếu Quý khách nhận sản phẩm tại các Showroom xin vui lòng chờ để nhân viên NIIT-ICT thực hiện xuất hàng, kiểm tra, cài đặt (nếu cần), sau đó sẽ bàn giao tới Quý khách.<br> 3) Nếu Quý khách nhận sản phẩm tại địa điểm yêu cầu, Quý khách có thể sắp xếp thời gian đi cùng nhân viên giao hàng của NIIT-ICT hoặc ra về trước, sau khi hẹn thời gian giao hàng phù hợp. Nhân viên giao hàng NIIT-ICT trước khi đi giao sẽ chủ động liên hệ tới Quý khách để xác nhận.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Mua hàng Online: </span></strong></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">- Chậm nhất sau 30 phút làm việc kể từ thời điểm nhận được đơn đặt hàng của khách hàng, nhân viên của chúng tôi sẽ liên lạc trực tiếp với khách hàng hoặc gửi email xác nhận việc nhận được thông tin đặt hàng từ Quý khách, đồng ý đơn đặt hàng hay từ chối đơn đặt hàng của Quý khách (nêu rõ lý do từ chối cung cấp). Trường hợp Quý khách đặt hàng ngoài giờ làm việc, chúng tôi sẽ liên lạc lại với Quý khách vào ngày làm việc kế tiếp. </span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Xem hướng dẫn </span></strong><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">mua hàng Online<strong> chi tiết tại đây:</strong></span></strong><span style="font-size: 11.0pt; line-height: 150%; color: #222222;">&nbsp;</span><span style="color: #0000ff;"><a style="color: #0000ff;" href="https://www.phucanh.vn/page/huong-dan-mua-hang-online"><strong><em><span style="font-size: 11.0pt; line-height: 150%;">https://www.phucanh.vn/page/huong-dan-mua-hang-online</span></em></strong></a></span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">* Lưu ý: </span></strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Đối với những đơn hàng phải gửi qua trung gian vận chuyển, chúng tôi sẽ tiến hành đóng gói, niêm phong toàn bộ gói hàng để Quý khách hoàn toàn yên tâm rằng gói hàng không bị thay đổi nội dung khi vận chuyển.</span></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Chúng tôi sẽ thông báo cho Quý khách thời gian dự kiến hàng được chuyển tới, như vậy Quý khách hàng yên tâm rằng gói hàng đã được giao và sắp xếp thời gian nhận hàng.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-size: 11pt; line-height: 150%; color: black; font-family: 'times new roman', times;">Ngay khi nhận hàng từ người chuyển phát hàng, Quý khách hàng vui lòng trực tiếp kiểm tra kỹ hàng hóa, nếu phát sinh các vấn đề liên quan đến chủng loại, chất lượng, số lượng hàng hoá không đúng như trong đơn đặt hàng hay niêm phong bị thay đổi, Quý khách hãy lập biên bản khi nhận hàng với đơn vị hoặc người chuyển phát và thông báo ngay cho Công ty NIIT-ICT để cùng phối hợp xử lý. Trong trường hợp như vậy, Quý khách không phải chịu bất kỳ trách nhiệm nào liên quan tới việc hàng hoá bị thay đổi, thất lạc, không đảm bảo về chất lượng và số lượng trong quá trình vận chuyển hàng hoá tới địa chỉ của khách hàng.</span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><em><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">Khi cần biết thêm thông tin chi tiết hoặc có yêu cầu khác, Quý khách hãy liên hệ ngay với chúng tôi, hotline: 1900 2164 Chúng tôi rất hân hạnh được phục vụ Quý khách!</span></strong></em></span></p>
            <p style="margin: 0cm; margin-bottom: .0001pt; text-align: right; line-height: 150%; background: white;"><span style="font-family: 'times new roman', times;"><em><strong><span style="font-size: 11.0pt; line-height: 150%; color: black;">NIIT-ICT Smart World</span></strong></em></span></p>
        </div>
    </div>
@endsection
